<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-T7EHHSF" failures="1" tests="11" name="com.testng.ITest" time="0.625" errors="0" timestamp="2025-09-10T20:15:15 IST" skipped="10">
  <testcase classname="com.testng.ITest" name="testMethod" time="0.054">
    <skipped/>
  </testcase> <!-- testMethod -->
  <testcase classname="com.testng.ITest" name="testMethod" time="0.107">
    <skipped/>
  </testcase> <!-- testMethod -->
  <testcase classname="com.testng.ITest" name="testMethod" time="0.024">
    <skipped/>
  </testcase> <!-- testMethod -->
  <testcase classname="com.testng.ITest" name="testMethod" time="0.033">
    <skipped/>
  </testcase> <!-- testMethod -->
  <testcase classname="com.testng.ITest" name="testMethod" time="0.075">
    <skipped/>
  </testcase> <!-- testMethod -->
  <testcase classname="com.testng.ITest" name="testMethod" time="0.086">
    <skipped/>
  </testcase> <!-- testMethod -->
  <testcase classname="com.testng.ITest" name="testMethod" time="0.040">
    <skipped/>
  </testcase> <!-- testMethod -->
  <testcase classname="com.testng.ITest" name="testMethod" time="0.025">
    <failure message="expected [google] but found [Google]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [google] but found [Google]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.testng.ITest.testMethod(ITest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testMethod -->
  <testcase classname="com.testng.ITest" name="testMethod" time="0.068">
    <skipped/>
  </testcase> <!-- testMethod -->
  <testcase classname="com.testng.ITest" name="testMethod" time="0.028">
    <skipped/>
  </testcase> <!-- testMethod -->
  <testcase classname="com.testng.ITest" name="testMethod" time="0.085">
    <skipped/>
  </testcase> <!-- testMethod -->
</testsuite> <!-- com.testng.ITest -->
